import type { Meta, StoryObj } from "@storybook/react";
import { Heading } from "~/components/head";
// Adjust the import path accordingly

const meta = {
  title: "Components/Heading", // Storybook category and component name
  component: Heading, // Component that we're creating the story for
  tags: ["autodocs"], // Optional, helps with autogenerated docs
  parameters: {
    layout: "centered", // Centers the component in Storybook preview
  },
} satisfies Meta<typeof Heading>;

export default meta;
type Story = StoryObj<typeof meta>;

// Default Story
export const Default: Story = {
  args: {
    children: "This is a default Heading", // The text content for the heading
    level: 1, // Default level (h1 equivalent)
    align: "auto", // Default alignment (auto)
    weight: "medium", // Default weight (medium)
  },
};

// Custom Level Story
export const CustomLevel: Story = {
  args: {
    children: "This is a Heading with Level 3",
    level: 3, // This will render <h3>
    align: "auto", // Default alignment
    weight: "regular", // Regular font weight
  },
};

// Aligned Headings Story
export const AlignedHeadings: Story = {
  args: {
    children: "This is a Heading with Center Alignment",
    level: 2, // This will render <h2>
    align: "center", // Center-aligned text
    weight: "bold", // Bold font weight
  },
};

// Weighted Headings Story
export const WeightedHeadings: Story = {
  args: {
    children: "This is a Bold Heading",
    level: 2, // This will render <h2>
    align: "start", // Left-aligned text
    weight: "bold", // Bold font weight
  },
};

// Custom Element Story
export const CustomElement: Story = {
  args: {
    children: "This is a Heading rendered as a div",
    level: 2, // This will render <div>
    as: "div", // Rendering as a div instead of an h2
    align: "auto", // Default alignment
    weight: "medium", // Default weight
  },
};
