import type { Meta, StoryObj } from "@storybook/react";
import { Model } from "~/components/model";
// Adjust the import path accordingly

const meta = {
  title: "Components/Model", // Storybook category and component name
  component: Model, // Component that we're creating the story for
  tags: ["autodocs"], // Optional, helps with autogenerated docs
  parameters: {
    layout: "fullscreen", // Centers the component in Storybook preview
  },
} satisfies Meta<typeof Model>;

export default meta;
type Story = StoryObj<typeof meta>;

// Default Story
export const Default: Story = {
  args: {
    models: [
      {
        position: { x: 0, y: 0, z: 0 },
      },
    ], // Sample model data to display
    show: true, // Whether the model is visible
    showDelay: 0, // No delay for the model to appear
    cameraPosition: { x: 0, y: 0, z: 8 }, // Camera position
    alt: "3D Model", // Alt text for the model
  },
};

// Model with Multiple Models
export const MultipleModels: Story = {
  args: {
    models: [
      { position: { x: -2, y: 0, z: 0 } },
      { position: { x: 2, y: 0, z: 0 } },
    ], // Display multiple models in different positions
    show: true,
    showDelay: 0,
    cameraPosition: { x: 0, y: 0, z: 8 },
    alt: "3D Model with multiple instances",
  },
};

// Custom Camera Position Story
export const CustomCameraPosition: Story = {
  args: {
    models: [
      {
        position: { x: 0, y: 0, z: 0 },
      },
    ],
    show: true,
    showDelay: 0,
    cameraPosition: { x: 5, y: 5, z: 15 }, // Custom camera position
    alt: "3D Model with custom camera position",
  },
};

// Model with Delayed Show
export const DelayedShow: Story = {
  args: {
    models: [
      {
        position: { x: 0, y: 0, z: 0 },
      },
    ],
    show: true,
    showDelay: 1000, // 1 second delay before the model appears
    cameraPosition: { x: 0, y: 0, z: 8 },
    alt: "3D Model with delayed show",
  },
};

// Model with Hidden Show
export const HiddenShow: Story = {
  args: {
    models: [
      {
        position: { x: 0, y: 0, z: 0 },
      },
    ],
    show: false, // Model is hidden
    showDelay: 0,
    cameraPosition: { x: 0, y: 0, z: 8 },
    alt: "Hidden 3D Model",
  },
};
